package com.example.transportapp.data.transport.documents

/**
 * S22 (D60) — inline HTML for the fixed-format operational documents: loading challan,
 * freight bill, money receipt, and the party statement. Unlike the bilty (a
 * user-serviceable doc-engine template), these are company-form documents whose layout
 * never changes — so they render from Kotlin string templates straight to the same A4
 * WebView byte path the bilty uses. Money is pre-formatted paise; escaping is the
 * caller's (values are numeric or already-screened names).
 */
object OperationalDocuments {

    private const val HEAD =
        """
        <!DOCTYPE html><html><head><meta charset="utf-8"><style>
        @page { size: A4; margin: 14mm; }
        body { font-family: 'IBM Plex Sans', sans-serif; color: #111; margin: 0; }
        .head { text-align: center; border-bottom: 2px solid #111; padding-bottom: 8px; margin-bottom: 12px; }
        .head h1 { font-family: 'Anek Latin', sans-serif; font-size: 22px; margin: 0; letter-spacing: 1px; }
        .head .doc { font-size: 12px; letter-spacing: 3px; margin-top: 2px; }
        .meta { width: 100%; font-size: 11px; margin-bottom: 10px; }
        .meta td { padding: 2px 4px; }
        table { width: 100%; border-collapse: collapse; font-size: 11px; }
        th, td { border: 1px solid #999; padding: 5px 6px; text-align: left; }
        th { background: #EFEFEA; font-weight: 600; }
        .num { text-align: right; font-family: 'IBM Plex Mono', monospace; }
        .totals td { border: none; padding: 3px 6px; }
        .totals .label { text-align: right; font-weight: 600; }
        .totals .grand { font-weight: 700; font-size: 13px; border-top: 1px solid #111; }
        .sign { margin-top: 40px; width: 100%; font-size: 10px; }
        .sign td { border: none; text-align: center; }
        .signline { border-top: 1px solid #111; width: 180px; margin: 0 auto 4px; height: 34px; }
        .terms { font-size: 9px; color: #444; margin-top: 16px; border-top: 1px solid #999; padding-top: 6px; }
        .stamp { border: 2px solid #5B2A86; color: #5B2A86; padding: 2px 8px; display: inline-block;
                 transform: rotate(-3deg); font-family: 'IBM Plex Mono', monospace; font-size: 11px; }
        </style></head><body>
        """

    private fun page(title: String, docType: String, body: String): String =
        HEAD +
            "<div class=\"head\"><h1>$title</h1><div class=\"doc\">$docType</div></div>" +
            body +
            "<table class=\"sign\"><tr>" +
            "<td><div class=\"signline\"></div>Driver's signature</td>" +
            "<td><div class=\"signline\"></div>Consignee's signature</td>" +
            "<td><div class=\"signline\"></div>For $title</td>" +
            "</tr></table>" +
            "<div class=\"terms\">Goods booked at Owner's risk. Subject to the origin branch's jurisdiction. " +
            "This document was generated by TransportApp.</div></body></html>"

    private fun meta(vararg pairs: Pair<String, String>): String {
        val sb = StringBuilder("<table class=\"meta\">")
        var i = 0
        while (i < pairs.size) {
            sb.append("<tr>")
            sb.append("<td><b>").append(pairs[i].first).append(":</b> ").append(pairs[i].second).append("</td>")
            if (i + 1 < pairs.size) {
                sb.append("<td><b>").append(pairs[i + 1].first).append(":</b> ").append(pairs[i + 1].second).append("</td>")
            }
            sb.append("</tr>")
            i += 2
        }
        sb.append("</table>")
        return sb.toString()
    }

    /** The loading challan for one trip (§11). */
    fun challan(
        challanNo: String,
        companyName: String,
        companyAddress: String,
        vehicle: String,
        driver: String,
        driverLicence: String,
        from: String,
        to: String,
        via: List<String>,
        consignments: List<ChallanLine>,
        hire: String,
        advance: String,
        balance: String,
        created: String,
    ): String {
        val viaText = if (via.isNotEmpty()) " via " + via.joinToString(", ") else ""
        val rows = consignments.joinToString("") { c ->
            "<tr><td>${c.bilty}</td><td>${c.consignee}</td><td>${c.from}</td><td>${c.to}</td>" +
                "<td class=\"num\">${c.packages}</td><td class=\"num\">${c.weightKg} kg</td><td class=\"num\">${c.amount}</td></tr>"
        }
        val body =
            meta(
                "Challan No" to challanNo,
                "Date" to created,
                "Vehicle" to vehicle,
                "From" to from,
                "Driver" to driver,
                "To" to to + viaText,
                "Licence" to driverLicence,
                "Company" to companyName,
            ) +
                "<table><tr><th>Bilty No</th><th>Consignee</th><th>From</th><th>To</th>" +
                "<th>Pkgs</th><th>Weight</th><th class=\"num\">Freight</th></tr>" +
                rows +
                "</table>" +
                "<table class=\"totals\"><tr><td class=\"label\">Total load</td><td class=\"num\">" +
                "${consignments.sumOf { it.weightKg }} kg</td></tr>" +
                "<tr><td class=\"label\">Lorry hire</td><td class=\"num\">$hire</td></tr>" +
                "<tr><td class=\"label\">Advance paid</td><td class=\"num\">$advance</td></tr>" +
                "<tr><td class=\"label\">Balance to driver</td><td class=\"num\">$balance</td></tr></table>"
        return page(companyName, "LOADING CHALLAN", body)
    }

    data class ChallanLine(
        val bilty: String,
        val consignee: String,
        val from: String,
        val to: String,
        val packages: Int,
        val weightKg: Long,
        val amount: String,
    )

    /** The freight bill for one party (§12). */
    fun freightBill(
        billNo: String,
        companyName: String,
        companyAddress: String,
        companyGstin: String,
        partyName: String,
        partyGstin: String,
        from: String,
        to: String,
        period: String,
        consignments: List<BillLine>,
        freight: String,
        charges: List<Pair<String, String>>,
        gst: String,
        total: String,
        issued: String,
    ): String {
        val rows = consignments.joinToString("") { c ->
            "<tr><td>${c.bilty}</td><td>${c.date}</td><td class=\"num\">${c.packages}</td>" +
                "<td class=\"num\">${c.weightKg} kg</td><td class=\"num\">${c.rate}</td><td class=\"num\">${c.amount}</td></tr>"
        }
        val chargeRows = charges.joinToString("") { (label, value) ->
            "<tr><td colspan=\"5\">$label</td><td class=\"num\">$value</td></tr>"
        }
        val body =
            meta(
                "Bill No" to billNo,
                "Issued" to issued,
                "Party" to partyName,
                "GSTIN" to partyGstin,
                "Route" to "$from - $to",
                "Period" to period,
            ) +
                "<table><tr><th>Bilty No</th><th>Date</th><th>Pkgs</th><th>Chargeable</th>" +
                "<th class=\"num\">Rate</th><th class=\"num\">Freight</th></tr>" +
                rows + chargeRows +
                "</table>" +
                "<table class=\"totals\">" +
                "<tr><td class=\"label\">Taxable value</td><td class=\"num\">$freight</td></tr>" +
                "<tr><td class=\"label\">GST</td><td class=\"num\">$gst</td></tr>" +
                "<tr><td class=\"label grand\">Grand total</td><td class=\"num grand\">$total</td></tr></table>"
        return page(companyName, "FREIGHT BILL", body)
    }

    data class BillLine(
        val bilty: String,
        val date: String,
        val packages: Int,
        val weightKg: Long,
        val rate: String,
        val amount: String,
    )

    /** The money receipt for a collection (§12.2). */
    fun receipt(
        receiptNo: String,
        companyName: String,
        companyAddress: String,
        partyName: String,
        amount: String,
        inWords: String,
        mode: String,
        towards: String,
        collected: String,
        collectedBy: String,
    ): String {
        val body =
            meta(
                "Receipt No" to receiptNo,
                "Date" to collected,
                "Received from" to partyName,
                "Mode" to mode,
                "Towards" to towards,
                "Collected by" to collectedBy,
            ) +
                "<table class=\"totals\">" +
                "<tr><td class=\"label grand\">Rupees received</td><td class=\"num grand\">$amount</td></tr></table>" +
                "<p style=\"font-size:11px\">$inWords only.</p>"
        return page(companyName, "MONEY RECEIPT", body)
    }

    /** The party statement of account for a period (§12.3). */
    fun statement(
        partyName: String,
        companyName: String,
        from: String,
        to: String,
        opening: String,
        rows: List<StatementLine>,
        closing: String,
    ): String {
        val table = if (rows.isEmpty()) {
            "<p style=\"font-size:11px\">No transactions in this period.</p>"
        } else {
            "<table><tr><th>Date</th><th>Particulars</th><th>Document</th>" +
                "<th class=\"num\">Debit</th><th class=\"num\">Credit</th></tr>" +
                rows.joinToString("") { r ->
                    "<tr><td>${r.date}</td><td>${r.particulars}</td><td>${r.doc}</td>" +
                        "<td class=\"num\">${r.debit.ifEmpty { "-" }}</td><td class=\"num\">${r.credit.ifEmpty { "-" }}</td></tr>"
                } + "</table>"
        }
        val body =
            meta("Party" to partyName, "Period" to "$from - $to") +
                table +
                "<table class=\"totals\">" +
                "<tr><td class=\"label\">Opening balance</td><td class=\"num\">$opening</td></tr>" +
                "<tr><td class=\"label grand\">Closing balance</td><td class=\"num grand\">$closing</td></tr></table>"
        return page(companyName, "STATEMENT OF ACCOUNT", body)
    }

    data class StatementLine(
        val date: String,
        val particulars: String,
        val doc: String,
        val debit: String,
        val credit: String,
    )
}
